server:
  port: 1000
spring:
  application:
    name: msc-gateway
  cloud:
    # 指定nacos注册中心的地址
    nacos:
      config:
        server-addr: 127.0.0.1:8848,127.0.0.1:8847,127.0.0.1:8849
        file-extension: yml
        namespace: c0709089-f90b-4917-b492-3b39d40e526b
    gateway:
      discovery:
        locator:
          # 配置开启与DiscoveryClient整合
          enabled: true
      routes:
        # 路由id
        - id: payment_route
          # 路由uri地址, loadbalancer://服务名称 【DNS域名解析的思路】
          uri: lb://msc-payment
          predicates:
            # 拦截所有提供者的请求到提供者集群服务
            - Path=/api-payment/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        # 路由id
        - id: order_route
          # 路由uri地址, loadbalancer://服务名称 【DNS域名解析的思路】
          uri: lb://msc-order
          predicates:
            # 拦截所有提供者的请求到提供者集群服务
            - Path=/api-order/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader